## import 

In [33]:
import numpy as np
import cv2

In [34]:
img = cv2.imread('./images/single5.jpeg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
# laod cascade classifier - fronatalface
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

In [36]:
# apply cascade classifier to an img
faces,num_detection = face_cascade.detectMultiScale2(img)

In [37]:
print(faces)

[[245 118 235 235]]


In [38]:
print(num_detection)

[78]


In [39]:
pt1 = (245,118)
pt2 = (245+235, 118+235)
cv2.rectangle(img,pt1,pt2,(0,255,0))

cv2.imshow('face_detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
# draw the cirlce
cx = 245 + 235 //2
cy = 118 + 235//2
r = 235 // 2
cv2.circle(img,(cx,cy),r,(0,255,255),2)
cv2.imshow('face detection circle',img)
cv2.waitKey()
cv2.destroyAllWindows()

## Multiple face detection

In [41]:
img = cv2.imread('./images/three_normal1.jpeg')

In [42]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [43]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

# step1: apply cascade classifier to an image
faces, num_detection = face_cascade.detectMultiScale2(img,minNeighbors=8)

#step2: run a loop
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))

#step3: display the image
cv2.imshow('face detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

print(faces)

[[ 87  38 165 165]
 [462  23 210 210]
 [295  68 175 175]]


In [44]:
print(num_detection)


[132  27  67]


## Face & Eyes detections

In [45]:
img = cv2.imread('./images/three_normal1.jpeg')

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')



In [47]:
faces, num_detection_face = face_cascade.detectMultiScale2(img,minNeighbors=8)
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))
    
    #step2: croping the face
    face_roi = img[y:y+h,x:x+h] # croping the image
    #step3: apply to cascade classifier(eye)
    eyes,num_detection_eyes = eye_cascade.detectMultiScale2(face_roi)
    for ex, ey, ew, eh in eyes:
        cx = x+ex + ew // 2
        cy = y+ey + eh // 2
        r = eh //2
        cv2.circle(img,(cx,cy),r,(255,0,255),2)
    
#step4:
cv2.imshow("face eye detection",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
        

## Faces, Eyes, Smiles Detection

In [48]:
img = cv2.imread('./images/three_normal1.jpeg')

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [49]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')
smile_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_smile.xml')

In [50]:
# Step1: Face Detection
faces, num_detection_face = face_cascade.detectMultiScale2(img,minNeighbors=8)
for x,y,w,h in faces:
    face_roi = img[y:y+h,x:x+h].copy() # croping the image
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))

    #step2: apply to cascade classifier(eye)
    eyes,num_detection_eyes = eye_cascade.detectMultiScale2(face_roi)
    for ex, ey, ew, eh in eyes:
        cx = x+ex + ew // 2
        cy = y+ey + eh // 2
        r = eh //2
        cv2.circle(img,(cx,cy),r,(255,0,255),2)
        
    #step3: smile detection
    smiles , num_detection_smile = smile_cascade.detectMultiScale2(face_roi)
    for sx,sy,sw,sh in smiles:
        cv2.rectangle(img,(x+sx,y+sy),(x+sx+sw,y+sy+sh),(255,0,0),2)
    
#step4:
cv2.imshow("face eye smile detection",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
        